# Generated by Django 2.0.7 on 2018-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (3, 'On the way'), (1, 'Cooking'), (4, 'Delivered')]),
        ),
    ]
