# Generated by Django 2.0.7 on 2018-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180713_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (3, 'On the way'), (4, 'Delivered'), (1, 'Cooking')]),
        ),
    ]
