# Generated by Django 2.0.7 on 2018-07-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180714_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='price',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (2, 'Ready'), (3, 'On the way'), (1, 'Cooking')]),
        ),
    ]
