# Generated by Django 2.0.7 on 2018-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180714_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='quantity',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (4, 'Delivered'), (1, 'Cooking'), (3, 'On the way')]),
        ),
    ]
