# Generated by Django 2.0.7 on 2018-07-14 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180714_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='meal',
            name='server_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (2, 'Ready'), (1, 'Cooking'), (3, 'On the way')]),
        ),
    ]
