# Generated by Django 2.0.7 on 2018-07-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180714_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='server_time',
            new_name='server_time_from',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cooking'), (3, 'On the way'), (2, 'Ready'), (4, 'Delivered')]),
        ),
    ]
