# Generated by Django 2.0.7 on 2018-07-14 04:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180714_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='server_time_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2018, 7, 14, 23, 24, 55, 46202)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='server_time_from',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (3, 'On the way'), (1, 'Cooking'), (4, 'Delivered')]),
        ),
    ]
