# Generated by Django 2.0.7 on 2018-07-14 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180714_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='server_time_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 14, 16, 35, 47, 48447)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (1, 'Cooking'), (3, 'On the way'), (2, 'Ready')]),
        ),
    ]
