# Generated by Django 2.0.7 on 2018-07-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180714_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='server_time_from',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='server_time_to',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='sub_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the way'), (4, 'Delivered'), (1, 'Cooking'), (2, 'Ready')]),
        ),
    ]
